### ISSUE TITLE
Make bin/hey a separate flake

### ISSUE THREAD

**Issue by BentonEdmondson** [hlissner/dotfiles#21]
Have you considered making `bin/hey` a separate flake? As you say, it simplifies the commands a lot and makes it a bit more like the Guix UI. I see you have some aspects of it that are specific to your dotfiles, which would need to be removed, but the generic commands would still be useful on any system. Thoughts?

**Comment by hlissner** [comment]
Sorry for the late response. I appreciate the thought, but I don't have the time nor the nix-fu to generalize a generalized `bin/hey`.

This repo is my journey to learn NixOS. It is an ongoing experiment, and I'm not far enough along to call myself an expert or authority -- certainly not enough to maintain tooling for the nix ecosystem.

When (and if) the day comes I can call myself an expert, I may reconsider, but you'd have better luck tracking [devos](https://github.com/divnix/devos).

Otherwise, feel free to extract whatever you like from my dotfiles; I wouldn't mind if you took `bin/hey` verbatim and realized a generalized version of it yourself. Or better, start a conversation about how nix tooling could be improved upstream; that benefits everyone.

Since this is an awfully old issue, I'll close this, but feel free to follow up here if you'd like.
