### ISSUE TITLE
Shiro external monitor

### ISSUE THREAD

**Issue by LeoQiao18** [hlissner/dotfiles#29]
### What would you like to know?

For the `shiro` host, you mention in the README about external monitor setup. Do you manually run the `xrandr` command every time you connect with/disconnect from the external monitor, or do you automate it somehow?

Your configuration is great btw!

**Comment by hlissner** [comment]
Sorry for the late response! Yes, I run the command manually, but it happens so rarely (maybe 2-3 times a year?) that I forget the exact command, so I keep it in the README (and since it's an org file, I can execute the block directly in Emacs).

I suppose I could automate it with udev (something [like this](https://tyler.vc/auto-monitor-detection-on-linux)), but like I said, I don't need it often enough to warrant the effort.

Hope that answers your question!
